import type { Metadata } from "next";
import { Playfair_Display, Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider";
import { PageTitleManager } from "@/components/page-title-manager";
import { AppPatternBackground } from "@/components/app-pattern-background";

const inter = Inter({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
	variable: "--font-sans",
	display: "swap",
});

const playfairDisplay = Playfair_Display({
	subsets: ["latin"],
	weight: ["400", "600", "700", "800", "900"],
	style: ["normal", "italic"],
	variable: "--font-display",
	display: "swap",
});

export const metadata: Metadata = {
	title: {
		default: "STG SMK Penanti",
		template: "%s | STG SMK Penanti",
	},
	description: "Generated by create next app",
	icons: {
		icon: "/img/smkp-logo.svg",
	},
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${inter.variable} ${playfairDisplay.variable} font-sans antialiased`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<PageTitleManager />
					<AppPatternBackground>{children}</AppPatternBackground>
				</ThemeProvider>
				<Toaster richColors position="bottom-right" />
			</body>
		</html>
	);
}
